#define __OPT_ABLELOCK__ no
#define OPT_ABLELOCK_no
#define __OPT_ARCH__ x86_64
#define OPT_ARCH_x86_64
#define __OPT_ASLR__ yes
#define OPT_ASLR_yes
#define __OPT_CERTICOM__ no
#define OPT_CERTICOM_no
#define __OPT_CRYPTODEV__ no
#define OPT_CRYPTODEV_no
#define __OPT_DATA_INODES__ 3000
#define OPT_DATA_INODES_3000
#define __OPT_DATA_SIZE__ 60
#define OPT_DATA_SIZE_60
#define __OPT_EXTRA_DIRS__ none
#define OPT_EXTRA_DIRS_none
#define __OPT_GRAPHICS__ no
#define OPT_GRAPHICS_no
#define __OPT_GUEST__ none
#define OPT_GUEST_none
#define __OPT_HOSTNAME__ Local_VM71
#define OPT_HOSTNAME_Local_VM71
#define __OPT_IP__ dhcp
#define OPT_IP_dhcp
#define __OPT_MACADDR__ 52:54:00:ae:86:22
#define __OPT_NFS__ no
#define OPT_NFS_no
#define __OPT_PATHTRUST__ no
#define OPT_PATHTRUST_no
#define __OPT_PERL__ no
#define OPT_PERL_no
#define __OPT_POLICY__ none
#define OPT_POLICY_none
#define __OPT_PYTHON__ no
#define OPT_PYTHON_no
#define __OPT_QAUDIT__ no
#define OPT_QAUDIT_no
#define __OPT_QFIM__ no
#define OPT_QFIM_no
#define __OPT_QTD__ no
#define OPT_QTD_no
#define __OPT_QVM__ no
#define OPT_QVM_no
#define __OPT_REPOS__ /cygdrive/C//Users/david/qnx710/target/qnx7
#define __OPT_ROOT__ no
#define OPT_ROOT_no
#define __OPT_SAFE__ no
#define OPT_SAFE_no
#define __OPT_SECPOL__ no
#define OPT_SECPOL_no
#define __OPT_SECURE_DATA__ no
#define OPT_SECURE_DATA_no
#define __OPT_SECURE_PROCFS__ yes
#define OPT_SECURE_PROCFS_yes
#define __OPT_SLM__ no
#define OPT_SLM_no
#define __OPT_SSHD_PREGEN__ yes
#define OPT_SSHD_PREGEN_yes
#define __OPT_SSH_IDENT__ prompt
#define OPT_SSH_IDENT_prompt
#define __OPT_SYS_INODES__ 1000
#define OPT_SYS_INODES_1000
#define __OPT_SYS_SIZE__ 20
#define OPT_SYS_SIZE_20
#define __OPT_TCG__ no
#define OPT_TCG_no
#define __OPT_TELNET__ no
#define OPT_TELNET_no
#define __OPT_TOMCRYPT__ no
#define OPT_TOMCRYPT_no
#define __OPT_TOYBOX__ no
#define OPT_TOYBOX_no
#define __OPT_TYPE__ vmware
#define OPT_TYPE_vmware
#define __OPT_TZ__ UTC0
#define OPT_TZ_UTC0
#define __OPT_UNION__ yes
#define OPT_UNION_yes
#define __OPT_USB__ no
#define OPT_USB_no
#define __OPT_VALGRIND__ no
#define OPT_VALGRIND_no
#define __OPT_VERBOSE__ no
#define OPT_VERBOSE_no
#define __OPT_ZONEINFO__ no
#define OPT_ZONEINFO_no
